# -*- coding: utf-8 -*-
"""FSTAPPFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNeWn4FxqnEZ0fmgcYkZTSpYf7dBzmds
"""

import streamlit as st # Framework of Web Development usinhg ML
import pickle          # Load model
model=pickle.load(open("bestrbf.pickle","rb"))
st.title("Web API for Classification")
variance=st.text_input("Variance:",value=0.0)
skewness=st.text_input("Skewness:",value=0.0)
curtosis=st.text_input("Curtosis:",value=0.0)
entropy=st.text_input("Entropy:",value=0.0)
X=[[float(variance),float(skewness),float(curtosis),float(entropy)]]
y=model.predict(X)
if st.button("Predict"):
  st.success(y)